/**
 * Mock Data Repository for AI Social Media Agent Workspace
 * Contains seed posts, scheduled items, simulated agent configurations, and logs.
 */

window.SocialMediaMockData = {
    // Initial posts lists
    posts: [
        {
            id: "post-1",
            platform: "linkedin",
            content: "🚀 AI Agents are revolutionizing modern enterprises! Today, we launched our new Model Context Protocol (MCP) framework, enabling seamless, secure, and governed tool calling. \n\nBy integrating directly with external APIs and databases through declarative JSON-RPC models, developers can unlock absolute autonomy in system workflows.\n\nAre you adopting MCP in your current systems? Let's discuss in the comments! 👇\n\n#ArtificialIntelligence #SoftwareEngineering #MCP #LangGraph #DataEngineering",
            mediaType: "image",
            mediaUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop",
            mediaIdea: "A glowing futuristic network topology visualization with nodes connecting gracefully.",
            status: "scheduled",
            scheduledTime: "2026-05-30T10:00:00",
            engagement: { likes: 0, comments: 0, shares: 0 },
            logs: ["Post generated by agent node 'draft_post'.", "Approved via Slack integration by sana18.", "Scheduled in workflow cron schedule."]
        },
        {
            id: "post-2",
            platform: "twitter",
            content: "LangGraph + HITL = 🚀\n\nHuman-in-the-Loop workflows are critical for reliable enterprise AI. By injecting verification gates before publishing, we get the efficiency of autonomous agents combined with human judgment and zero brand risk.\n\nHere is how our DAG works: 👇",
            mediaType: "none",
            mediaUrl: "",
            mediaIdea: "",
            status: "scheduled",
            scheduledTime: "2026-05-30T16:30:00",
            engagement: { likes: 0, comments: 0, shares: 0 },
            logs: ["Drafted post by agent model.", "Passed HITL gate with modifications.", "Added to Twitter cron queue."]
        },
        {
            id: "post-3",
            platform: "instagram",
            content: "Designing the future of AI Agent architecture with custom UI design systems. Combining deep dark modes, harmonious gradients, and micro-animations to make complex workflows feel seamless and alive. ✨🎨\n\nWhat does your dream workspace look like? Let us know below!\n\n#UIUX #DashboardDesign #ProductDesign #Aesthetics #WebDevelopment #CodingAesthetics",
            mediaType: "image",
            mediaUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=800&auto=format&fit=crop",
            mediaIdea: "A dark high-fidelity aesthetic computer interface showing dynamic animations and vibrant HSL color indicators.",
            status: "published",
            scheduledTime: "2026-05-28T14:15:00",
            engagement: { likes: 142, comments: 28, shares: 12 },
            logs: ["Agent drafted visual copy.", "Approved by user in HITL queue.", "Published successfully to Instagram Graph API."]
        },
        {
            id: "post-4",
            platform: "linkedin",
            content: "🚨 New Research Alert! We analyzed over 500 enterprise agent deployments in 2026. The number one bottleneck isn't model capacity—it's integration governance. \n\nSecurity architectures that lack unified context protocols suffer from excessive data leak risks and high API latency. Standardizing on tools like MCP resolves this instantly.\n\nRead our comprehensive breakdown here: https://example.com/agent-research",
            mediaType: "image",
            mediaUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=800&auto=format&fit=crop",
            mediaIdea: "A sleek security shield composed of high-tech data lines.",
            status: "review",
            scheduledTime: "2026-05-31T09:00:00",
            engagement: { likes: 0, comments: 0, shares: 0 },
            logs: ["Agent executed tool 'Web Search' on topic 'agent governance bottleneck'.", "Draft generated based on latest research insights.", "Pushed to Slack channel #social-approvals for review."]
        }
    ],

    // Agent generation templates
    templates: [
        {
            topic: "Modern Front-end Aesthetics",
            platform: "linkedin",
            tone: "Inspiring & Professional",
            prompt: "Modern web interfaces must prioritize high-fidelity visuals, harmonious palettes, and smooth micro-animations. A gorgeous UX builds trust instantly."
        },
        {
            topic: "Model Context Protocol",
            platform: "twitter",
            tone: "Excited & Tech-savvy",
            prompt: "MCP is standardizing tool-calling for agents. It separates models from server runtimes. Absolute game changer for secure system integrations!"
        },
        {
            topic: "LangGraph State Machines",
            platform: "linkedin",
            tone: "Educational",
            prompt: "LangGraph provides cyclic state management for agents, giving developers precise control over agentic paths and human authorization checkpoints."
        }
    ],

    // Log repository for simulated terminal logging
    systemLogs: [
        { time: "15:09:56", level: "INFO", message: "AI Social Media Agent environment initialized successfully." },
        { time: "15:10:01", level: "SUCCESS", message: "Established connection to Slack App Gateway (HITL Channel: #social-approvals)." },
        { time: "15:10:02", level: "INFO", message: "Cron scheduling daemon active: checking for updates every 60 seconds." },
        { time: "15:10:05", level: "SUCCESS", message: "OAuth verified for LinkedIn API (Token expires in 59 days)." },
        { time: "15:10:06", level: "SUCCESS", message: "OAuth verified for Twitter/X API (V2 Write scope enabled)." }
    ]
};
